### ISSUE TITLE
We need a get-start document to guide how to run the project.

### ISSUE THREAD

**Issue by azzgo** [greengerong/rebirth-admin#23]

**Comment by azzgo** [comment]
<img width="792" alt="screen shot 2017-07-29 at 13 09 30" src="https://user-images.githubusercontent.com/5636512/28742317-3902bb4c-745f-11e7-8485-2c154c0feaa4.png">
<img width="1439" alt="screen shot 2017-07-29 at 13 09 22" src="https://user-images.githubusercontent.com/5636512/28742319-3ae574cc-745f-11e7-9e80-043f2995a155.png">

**Comment by greengerong** [comment]
coremodule被注册了两次问题

**Comment by azzgo** [comment]
cool, login problem is fixed
