### ISSUE TITLE
I Can't Login the demo system

### ISSUE THREAD

**Issue by zhangwei8387** [greengerong/rebirth-admin#25]
Dear Sir
       When I used the Account --admin/admin or --user/user to login the system, 
       (https://greengerong.github.io/rebirth-admin/login)
      I got an error message like ' 输入的用户名或者密码无效!(测试账号：admin/admin、user/user)'.
      please tell me how to login,

 thank you very much

**Comment by WarnerHooh** [comment]
Hello @zhangwei8387 ,

Since the server side(login request) is not working yet for the online demo.
You can clone this repo then install and run `npm start`, this will run a mock server for you. Then try localhost:4200

Regards
